### ISSUE TITLE
money - NLnet

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/documents#14]
Yep :)

Just a quick question about finance. I see the line 1250 from NLnet.
From what I understand, I have to ask them the money, and it is for me.
(it is splitted somehow, but this is the rest)

Is it true?

Thanks @michielbdejong !

Pierre

**Comment by michielbdejong** [comment]
Correct!

**Comment by pierreozoux** [comment]
Ok, I didn't expect this new income :) This is the good news of the day :)
