### ISSUE TITLE
Forum is ready!

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/documents#20]
Please give me some feedback, and then I officially publish it!

https://forum.indie.host/

Cheers :)

**Comment by michielbdejong** [comment]
Cool! But sign up doesn't work, the email doesn't arrive.

**Comment by michielbdejong** [comment]
Ah, spam folder of course.

**Comment by michielbdejong** [comment]
Cool! All seems to be working fine. Are backups working?

**Comment by pierreozoux** [comment]
You got it in your spam folder? This is not normal, what is your email provider?

And yes, backups are working :)
