### ISSUE TITLE
New Sign-In & Support Buttons

### ISSUE THREAD

**Issue by elioqoshi** [indiehosters/documents#21]
Here are the new buttons :)
https://dl.dropboxusercontent.com/u/62482708/Indiehosters%20Buttons.zip

Preview:
![signin](https://cloud.githubusercontent.com/assets/5436686/11317583/91bd007e-9033-11e5-9d8e-8f4cd209c1e4.png)

![support-01](https://cloud.githubusercontent.com/assets/5436686/11317584/97d4f57a-9033-11e5-99e8-2ac3f5a1c856.png)
![support-02](https://cloud.githubusercontent.com/assets/5436686/11317585/97fbd208-9033-11e5-8096-aee326ed231f.png)
![support-03](https://cloud.githubusercontent.com/assets/5436686/11317586/97ff368c-9033-11e5-83c1-00735c6812bf.png)
![support-04](https://cloud.githubusercontent.com/assets/5436686/11317587/98010016-9033-11e5-8a97-24a3331667f3.png)

**Comment by elioqoshi** [comment]
@pierreozoux here we go

**Comment by pierreozoux** [comment]
Thanks @elioqoshi let me know if you need hosting :)

**Comment by pierreozoux** [comment]
I just published it: https://microblog.pierre-o.fr/2015/we-do-have-buttons-now-get-your-indieswag-and-your
